apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: ml-scraper
data:
  BROWSER: "firefox"
  HEADLESS: "true"
  LOG_LEVEL: "INFO"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "scraper_db"
  PRODUCTS: |
    bicicleta rodado 29
    iPhone 16 Pro Max
    GeForce RTX 5090
