apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: ml-scraper
data:
  BROWSER: "chrome"
  HEADLESS: "true"
  LOG_LEVEL: "INFO"
  PRODUCTS: |
    bicicleta rodado 29
    iPhone 16 Pro Max
    GeForce RTX 5090
