apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-output
  namespace: ml-scraper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
